server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8

spring:
  security:
#    user:
#      name: test
#      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 797123596387-ea0trqh82m3nqgs2q2muvl79ech53glq.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: xEjtpCupgJFR_DeMd29n
            client-secret: Y9Ir6MOOFe
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cw2m6xryal2i.ap-northeast-2.rds.amazonaws.com:3306/study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: junil
    password: 1q2w3e4r
    
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file:
  path: C:/junil/junil/workspace/git/springboot-security-20220808/upload/